### ISSUE TITLE
Opening a sub panel

### ISSUE THREAD

**Issue by vladimircezar** [bvanpeski/SystemPreferences#9]
Using open `x-apple.systempreferences:com.apple.LoginItems-Settings.extension` I am able to open this panel

<img width="487" alt="image" src="https://github.com/user-attachments/assets/7fa0a9cf-420a-46e3-bee7-798010372006">

but how can I open the Netwoks extension sub panel? I tried many combinations of network and extensions without any success. I tried to use the script to find the correct anchors but it did not work. Any idea?

Thank you for this repo and all information on your blog!

**Comment by bvanpeski** [comment]
As far as I'm aware, macOS does not expose System Settings sub-menus in a way that's scriptable with bash. If you were motivated enough you could get it done with AppleScript GUI scripting, but if you're looking for something easy like `open x-apple.systempreferences:com.apple.wifi-settings-extension?NetworkExtensions` please file feedback with Apple.
